config/routes.rb
IdeaEr4::Application.routes.draw do

  resources :units

  match '/contexts/:id/list' => "contexts#list", via: 'get'
  match '/contexts/:id/geosmapslist' => "geosmaps#list", via: 'get'
  match '/missions/:id/newchild' => "missions#newchild", via: 'get'
  match '/roles/:id/newchild' => "roles#newchild", via: 'get'
  match '/geosmaps/:id/display' => "geosmaps#display", via: 'get'
  match '/geosmaps/:id/currentmap' => "geosmaps#currentmap", via: 'get'
  resources :assets
  resources :people
  resources :sites
  resources :missions do
    resources :missions
    resources :contexts do
      resources :geosmaps
    end
    
  end
  resources :roles do
    resources :roles
  end
  
  match '/roles/:id/newaccount' => "users#newaccount", via: 'get'
  match '/users/destroyaccount/:id' => "users#destroyaccount", via: 'delete'
  match '/users/:id/editaccount' => "users#edit", via: 'get'
  match '/users/:id/edit' => "users#edit", via: 'put'
  resources :users 
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match "/register", to: 'users#new', via: 'get'
  match "/signin", to: 'sessions#new', via: 'get'
  match "/signout", to: 'sessions#destroy', via: 'delete'
  match "/help", to: 'static_pages#help', via: 'get'
  match "/about", to: 'static_pages#about', via: 'get'
  match "/contact", to: 'static_pages#contact', via: 'get'

  

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id         :integer          not null, primary key
#  firstname  :string(255)
#  lastname   :string(255)
#  lat        :float
#  lng        :float
#  speed      :float
#  course     :float
#  height     :float
#  status     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Person < ActiveRecord::Base
  
  has_many :roles, as: :enrollable
  has_one :user, through: :role
  validates :firstname, presence: true
  validates :lastname, presence: true

  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  def index
    @people = Person.all
  end

  # GET /people/1
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to @person, notice: 'Person was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      redirect_to @person, notice: 'Person was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to people_url, notice: 'Person was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def person_params
      params.require(:person).permit(:firstname, :lastname, :lat, :lng, :speed, :course, :height, :status)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :speed %><br>
    <%= f.text_field :speed %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table class="table table-bordered">
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Speed</th>
      <th>Course</th>
      <th>Height</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @people.each do |person| %>
      <tr>
        <td><%= person.firstname %></td>
        <td><%= person.lastname %></td>
        <td><%= person.lat %></td>
        <td><%= person.lng %></td>
        <td><%= person.speed %></td>
        <td><%= person.course %></td>
        <td><%= person.height %></td>
        <td><%= person.status %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @person.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @person.lastname %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @person.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @person.lng %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @person.speed %>
</p>

<p>
  <strong>Course:</strong>
  <%= @person.course %>
</p>

<p>
  <strong>Height:</strong>
  <%= @person.height %>
</p>

<p>
  <strong>Status:</strong>
  <%= @person.status %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>