config/routes.rb
IdeaEr4::Application.routes.draw do

  resources :units

  match '/contexts/:id/list' => "contexts#list", via: 'get'
  match '/contexts/:id/geosmapslist' => "geosmaps#list", via: 'get'
  match '/missions/:id/newchild' => "missions#newchild", via: 'get'
  match '/roles/:id/newchild' => "roles#newchild", via: 'get'
  match '/geosmaps/:id/display' => "geosmaps#display", via: 'get'
  match '/geosmaps/:id/currentmap' => "geosmaps#currentmap", via: 'get'
  resources :assets
  resources :people
  resources :sites
  resources :missions do
    resources :missions
    resources :contexts do
      resources :geosmaps
    end
    
  end
  resources :roles do
    resources :roles
  end
  
  match '/roles/:id/newaccount' => "users#newaccount", via: 'get'
  match '/users/destroyaccount/:id' => "users#destroyaccount", via: 'delete'
  match '/users/:id/editaccount' => "users#edit", via: 'get'
  match '/users/:id/edit' => "users#edit", via: 'put'
  resources :users 
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match "/register", to: 'users#new', via: 'get'
  match "/signin", to: 'sessions#new', via: 'get'
  match "/signout", to: 'sessions#destroy', via: 'delete'
  match "/help", to: 'static_pages#help', via: 'get'
  match "/about", to: 'static_pages#about', via: 'get'
  match "/contact", to: 'static_pages#contact', via: 'get'

  

end

app/models/asset.rb
# == Schema Information
#
# Table name: assets
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  type       :string(255)
#  lat        :float
#  lng        :float
#  speed      :float
#  course     :float
#  height     :float
#  status     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Asset < ActiveRecord::Base
  has_many :roles, as: :enrollable
  has_one :user, through: :role
  validates :name, presence: true

end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  # GET /assets
  def index
    @assets = Asset.all
  end

  # GET /assets/1
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  def create
    @asset = Asset.new(asset_params)

    if @asset.save
      redirect_to @asset, notice: 'Asset was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /assets/1
  def update
    if @asset.update(asset_params)
      redirect_to @asset, notice: 'Asset was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /assets/1
  def destroy
    @asset.destroy
    redirect_to assets_url, notice: 'Asset was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def asset_params
      params.require(:asset).permit(:name, :type, :lat, :lng, :speed, :course, :height, :status)
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= form_for(@asset) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :speed %><br>
    <%= f.text_field :speed %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<h1>Listing assets</h1>

<table class="table table-bordered">
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Speed</th>
      <th>Course</th>
      <th>Height</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.name %></td>
        <td><%= asset.type %></td>
        <td><%= asset.lat %></td>
        <td><%= asset.lng %></td>
        <td><%= asset.speed %></td>
        <td><%= asset.course %></td>
        <td><%= asset.height %></td>
        <td><%= asset.status %></td>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<br>

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/new.html.erb
<h1>New asset</h1>

<%= render 'form' %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @asset.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @asset.type %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @asset.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @asset.lng %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @asset.speed %>
</p>

<p>
  <strong>Course:</strong>
  <%= @asset.course %>
</p>

<p>
  <strong>Height:</strong>
  <%= @asset.height %>
</p>

<p>
  <strong>Status:</strong>
  <%= @asset.status %>
</p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>