config/routes.rb
IdeaEr4::Application.routes.draw do

  resources :units

  match '/contexts/:id/list' => "contexts#list", via: 'get'
  match '/contexts/:id/geosmapslist' => "geosmaps#list", via: 'get'
  match '/missions/:id/newchild' => "missions#newchild", via: 'get'
  match '/roles/:id/newchild' => "roles#newchild", via: 'get'
  match '/geosmaps/:id/display' => "geosmaps#display", via: 'get'
  match '/geosmaps/:id/currentmap' => "geosmaps#currentmap", via: 'get'
  resources :assets
  resources :people
  resources :sites
  resources :missions do
    resources :missions
    resources :contexts do
      resources :geosmaps
    end
    
  end
  resources :roles do
    resources :roles
  end
  
  match '/roles/:id/newaccount' => "users#newaccount", via: 'get'
  match '/users/destroyaccount/:id' => "users#destroyaccount", via: 'delete'
  match '/users/:id/editaccount' => "users#edit", via: 'get'
  match '/users/:id/edit' => "users#edit", via: 'put'
  resources :users 
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match "/register", to: 'users#new', via: 'get'
  match "/signin", to: 'sessions#new', via: 'get'
  match "/signout", to: 'sessions#destroy', via: 'delete'
  match "/help", to: 'static_pages#help', via: 'get'
  match "/about", to: 'static_pages#about', via: 'get'
  match "/contact", to: 'static_pages#contact', via: 'get'

  

end

app/models/mission.rb
# == Schema Information
#
# Table name: missions
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  parent_id   :integer
#

class Mission < ActiveRecord::Base
  
  acts_as_tree dependent: :delete_all, :with_advisory_lock => false
  has_many :contexts, dependent: :destroy
  validates :name, presence: true
  
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  
  def index
    @missions = Mission.all
  end
  
  def listcontexts
    redirect_to contexts_url    
  end

  def edit
    @mission = Mission.find(params[:id])
  end

  def update
    @mission = Mission.find(params[:id])

    respond_to do |format|
      if @mission.update_attributes(params[:mission].permit(:name, :description))
        format.html { redirect_to missions_path, notice: 'Mission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end


  def newchild

    @missionparent = Mission.find(params[:id])
    @mission = Mission.new

  end

  def create
    @mission = Mission.new(params[:mission].permit(:name, :description, :parent_id))
    @missionparent = Mission.find(@mission.parent_id)

    respond_to do |format|
      if @missionparent.children<<@mission
        format.html { redirect_to missions_path, notice: 'Sub-mission was successfully created.' }
        format.json { render json: @mission, status: :created, location: @mission }
      else
        format.html { render action: "newchild" }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end



  def show
    @mission = Mission.find(params[:id])
  end
  
  def destroy
    @mission = Mission.find(params[:id])
    @mission.destroy

    respond_to do |format|
      format.html { redirect_to missions_url }
      format.json { head :no_content }
    end
  end
  
  
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/_form.html.erb
<%= form_for(@mission) do |f| %>
  <% if @mission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mission.errors.count, "error") %> prohibited this mission from being saved:</h2>

      <ul>
      <% @mission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/missions/edit.html.erb
<h1>Editing mission</h1>

<%= render 'form' %>

<%= link_to 'Show', @mission %> |
<%= link_to 'Back', missions_path %>

app/views/missions/index.html.erb
<h1>Listing missions</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Id</th>
    <th>Parent</th>
    <th>      </th>
  </tr>

<% @missions.each do |mission| %>
  <tr>
    <td><%= button_to mission.name, {:controller=> 'contexts', :id=> mission.id,:action=> 'list'}, 
                                           :class=>"btn btn-warning", :method=> :get%></td>
    <td><%= mission.description %></td>
    <td><%= mission.id %></td>
    <td><%= mission.parent_id %></td>

    <td><%= button_to 'Organization', roles_path, :class=>"btn", :method=>:get %></td>
    <td><%= button_to 'Change', edit_mission_path(mission), :class=>"btn", :method=>:get %></td>
    <td><%= button_to 'New Sub-Missions',{:controller=> 'missions', :id=> mission.id,:action=> 'newchild'} , :class=>"btn btn-primary", :method=>:get %></td>
    <% if mission.id != 1 %>
    <td><%= button_to 'Delete',{:controller=> 'missions', :id=> mission.id,:action=> 'destroy'} , :class=>"btn btn-primary", :method=>:delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Mission', new_mission_path %>

app/views/missions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mission.name %>
</p>

<p>
  <b>Description:</b>
  <%= @mission.description %>
</p>

<p>
  <b>Id:</b>
  <%= @mission.id %>
</p>

<p>
  <b>Parent_id:</b>
  <%= @mission.parent_id %>
</p>


<%= link_to 'Edit', edit_mission_path(@mission) %> |
<%= link_to 'Back', missions_path %>